-- MySQL Script generated by MySQL Workbench
-- Fri Sep  6 20:48:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- ----------------------------------------------------
-- Table `mydb`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operador` (
  `id_doperador` INT NOT NULL AUTO_INCREMENT,
  `nombre_operario` VARCHAR(45) NOT NULL,
  `apellido_operario` VARCHAR(45) NOT NULL,
  `telefono_operario` INT NOT NULL,
  PRIMARY KEY (`id_doperador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`depiladora_laser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`depiladora_laser` (
  `numero_serie` INT NOT NULL,
  `fecha_adquisicion` DATE NOT NULL,
  `vida_util_bateria` TIME NOT NULL,
  `depiladora_disponible` TINYINT NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`numero_serie`),
  UNIQUE INDEX `observaciones_UNIQUE` (`observaciones` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_sesiones` (
  `id_sesion` INT NOT NULL,
  `fecha_sesion` DATETIME NOT NULL,
  `duracion_sesion` TIME NOT NULL,
  `intensidad_usado_sesion` INT NOT NULL,
  `observaciones` VARCHAR(250) NULL,
  `operador_id_doperador` INT NOT NULL,
  `depiladora_laser_numero_serie` INT NOT NULL,
  PRIMARY KEY (`id_sesion`),
  INDEX `fk_historial_sesiones_operador_idx` (`operador_id_doperador` ASC) VISIBLE,
  INDEX `fk_historial_sesiones_depiladora_laser1_idx` (`depiladora_laser_numero_serie` ASC) VISIBLE,
  CONSTRAINT `fk_historial_sesiones_operador`
    FOREIGN KEY (`operador_id_doperador`)
    REFERENCES `mydb`.`operador` (`id_doperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_sesiones_depiladora_laser1`
    FOREIGN KEY (`depiladora_laser_numero_serie`)
    REFERENCES `mydb`.`depiladora_laser` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
